version: '3'

services:
  trumbification:
    image: ghcr.io/matticoli/trumbification:main
    environment:
      - MAIL_API_KEY=""
      - MAIL_SENDER=""
      - MAIL_REPLYTO=""
      - BOT_TOKEN=""
      - HASH_SECRET=""
      - BOTOWNER_GUILD=""
      - BOTOWNER_ALERT_CHANNEL=""
      - BOTOWNER_MENTION=""
      - BOTOWNER_ALERT_ENABLED=""
    volumes:
      - /datastorage/trumbification:/usr/src/app/data
    restart: always